// Team classification: national teams -> "seleccion", clubs -> "club" with a league slug.
// League slugs mirror the categories the supplier itself uses in its nav.
module.exports = {
  // Selecciones
  "Alemania": { type: "seleccion" },
  "Argelia": { type: "seleccion" },
  "Argentina": { type: "seleccion" },
  "Brasil": { type: "seleccion" },
  "Croacia": { type: "seleccion" },
  "España": { type: "seleccion" },
  "Gales": { type: "seleccion" },
  "Grecia": { type: "seleccion" },
  "Inglaterra": { type: "seleccion" },
  "Italia": { type: "seleccion" },
  "Japon": { type: "seleccion" },
  "Uruguay": { type: "seleccion" },

  // Clubes
  "AC Milan": { type: "club", league: "liga-italiana", leagueName: "Liga Italiana" },
  "Milan": { type: "club", league: "liga-italiana", leagueName: "Liga Italiana", canonical: "AC Milan" },
  "Ajax": { type: "club", league: "resto-del-mundo", leagueName: "Resto del Mundo" },
  "Arsenal": { type: "club", league: "liga-inglesa", leagueName: "Liga Inglesa" },
  "Athletic Club Bilbao": { type: "club", league: "liga-espanola", leagueName: "Liga Española" },
  "Atletico Madrid": { type: "club", league: "liga-espanola", leagueName: "Liga Española" },
  "Barcelona": { type: "club", league: "liga-espanola", leagueName: "Liga Española" },
  "Bayern Munich": { type: "club", league: "liga-alemana", leagueName: "Liga Alemana" },
  "Benfica": { type: "club", league: "liga-portuguesa", leagueName: "Liga Portuguesa" },
  "Boca": { type: "club", league: "liga-argentina", leagueName: "Liga Argentina", displayName: "Boca Juniors" },
  "Chelsea": { type: "club", league: "liga-inglesa", leagueName: "Liga Inglesa" },
  "Corinthians": { type: "club", league: "liga-brasilena", leagueName: "Liga Brasileña" },
  "Flamengo": { type: "club", league: "liga-brasilena", leagueName: "Liga Brasileña" },
  "Galatasaray": { type: "club", league: "resto-del-mundo", leagueName: "Resto del Mundo" },
  "Inter": { type: "club", league: "liga-italiana", leagueName: "Liga Italiana" },
  "Juventus": { type: "club", league: "liga-italiana", leagueName: "Liga Italiana" },
  "Liverpool": { type: "club", league: "liga-inglesa", leagueName: "Liga Inglesa" },
  "Manchester City": { type: "club", league: "liga-inglesa", leagueName: "Liga Inglesa" },
  "Manchester United": { type: "club", league: "liga-inglesa", leagueName: "Liga Inglesa" },
  "Nacional": { type: "club", league: "resto-del-mundo", leagueName: "Resto del Mundo", displayName: "Nacional de Uruguay" },
  "PSG": { type: "club", league: "liga-francesa", leagueName: "Liga Francesa" },
  "Palmeiras": { type: "club", league: "liga-brasilena", leagueName: "Liga Brasileña" },
  "Racing Club": { type: "club", league: "liga-argentina", leagueName: "Liga Argentina" },
  "Real Betis": { type: "club", league: "liga-espanola", leagueName: "Liga Española" },
  "Real Madrid": { type: "club", league: "liga-espanola", leagueName: "Liga Española" },
  "River Plate": { type: "club", league: "liga-argentina", leagueName: "Liga Argentina" },
};
